apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: local-k8s-apps-repo
  namespace: argocd
type: Opaque
data:
  password: <replace-me-with-github-token-base64-encoded>
  project: bG9jYWwtazhz # local-k8s
  type: Z2l0 #git
  url: aHR0cHM6Ly9naXRodWIuY29tL3N0YXRoaXMtZGl0Yy9wcHAtY2xvdWQuZ2l0Cg== # https://github.com/stathis-ditc/ppp-cloud.git
  username: eA== #x


